_target_: pytorch_lightning.callbacks.ModelCheckpoint
#monitor: None
save_top_k: -1
verbose: True
dirpath: saved_models
filename: '{epoch}' #put back in when PL fixes this _{val/accuracy:.4f}'
save_on_train_epoch_end: True
every_n_epochs: 1
